

const API_URL = 'https://dev-sb-api.advantage-eclinical.com/studyBuilder';
const API_AUTH_TOKEN = 'eyJraWQiOiJJTjhraElkamVvQjhUR1NrMnk1UWhtNE5SWkJNLWpLLWhOWWpsVzNqa19BIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULnIwdWYwTm9xeFI4Y1FMWW5wOWRudlZmYlpxTTRKMGFhOFJueU1pVzJFQ2Mub2FyMjJ4NmNnZGtqekJVaGwyOTciLCJpc3MiOiJodHRwczovL2VtbWVzLm9rdGEuY29tL29hdXRoMi9kZWZhdWx0IiwiYXVkIjoiYXBpOi8vZGVmYXVsdCIsImlhdCI6MTcwOTg2MDg4NCwiZXhwIjoxNzA5ODY0NDg0LCJjaWQiOiIwb2EydTkxbnY2a0ROaXdLdTI5NyIsInVpZCI6IjAwdWt4ZGpsN2drck9MVVJUMjk3Iiwic2NwIjpbIm9mZmxpbmVfYWNjZXNzIiwicHJvZmlsZSIsImVtYWlsIiwib3BlbmlkIl0sImF1dGhfdGltZSI6MTcwOTg2MDY5MSwic3ViIjoiZS5zcmlrYW50aEBlbW1lcy5jb20ifQ.OcmIRrRmPboyBlQKyAdzVDlCLifo2Y9jabwZRdoefymzLRBCHyw2aZ6WWneMEjIfVFy-IA5vlKRjcbKWeOUKHfqG4-ICQgcBTW-Xr4w17e0-fr-CoQZUwcgT4ahTIAy9VWPeilkyivAxI11JhfeCpjsi4oeg_qEKIpmuW1UDHzXCmyDFVX5Yyrcj_ikfZ7ayuqcBB4k_fe4Tzi3V3130XzSUU57xmdyrzhiV7mx0HUlCkrcBiONMK73ZgMWBwnZaWXZl49kpM-3egZzyyEOOOeBo1IWLvD6lfITBrzZU1_rsUN4Szo4ItUj8_2laN-y59Qj4atAdk2CKUpFOsn3vtA';

export default {
  API_URL,
  API_AUTH_TOKEN
};
